### ISSUE TITLE
Bug console

### ISSUE THREAD

**Issue by LeonKazotaruu** [GroupeZ-dev/Plugins-Report#5]
### Terms

- [X] I'm using the very latest version of the plugin.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/GroupeZ-dev/Plugins-Report/issues) and haven't found any.
- [X] I already searched on the plugin wiki to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I enabled the debug mode in config.yml and sql debug

### Discord Username (optional)

Kazotaruu_

### Plugin

zItems

### Server Version

1.21.3

### Server Software

1.0.0

### Plugin Version

Current Purpur Version: 1.21.3-2358-16ce24a (MC: 1.21.3)*
* You are running the latest version
Previous: 1.21.1-131-84281ce (MC: 1.21.1)

### What happened?

Les blocks que je pose apparaissent dans la console

### Steps to reproduce the issue

pas vraiment de manipulations

### Full Server Log

no mclogs

### Other files, you can drag and drop them here to upload. (optional)

https://we.tl/t-DdFTzqwya7

**Comment by Traqueur-dev** [comment]
He doesn't have the last update.
It's fixed with the last update
